#!/bin/sh
#PBS -N cuffmerge
#PBS -q long
#PBS -l nodes=1:ppn=1
#PBS -o /lustre/user/hubenxia/data/Zika/cuffmerge.out
#PBS -e /lustre/user/hubenxia/data/Zika/cuffmerge.err

/lustre/user/hubenxia/data/cufflinks-2.2.1.Linux_x86_64/cuffmerge  -p  8  -g /lustre/user/hubenxia/data/NCBI_LncRNA/Homo_sapiens.GRCh38.83.gtf  -s /lustre/user/hubenxia/data/NCBI_LncRNA/Homo_sapiens.GRCh38.fa    /lustre/user/hubenxia/data/Zika/assembliescuffmerge.txt  -o /lustre/user/hubenxia/data/Zika/
