#!/bin/sh
#PBS -N cuffdiff_zika_paired
#PBS -q long
#PBS -l nodes=1:ppn=1
#PBS -o /lustre/user/hubenxia/data/Zika/cuffdiff_zika_paired.out
#PBS -e /lustre/user/hubenxia/data/Zika/cuffdiff_zika_paired.err

/lustre/user/hubenxia/data/cufflinks-2.2.1.Linux_x86_64/cuffdiff   -p 8 -L Zika,Control    -o /lustre/user/hubenxia/data/Zika/diff_zika_paired_out  -b /lustre/user/hubenxia/data/NCBI_LncRNA/Homo_sapiens.GRCh38.fa   -u   /lustre/user/hubenxia/data/Zika/merged_asm/merged.gtf  /lustre/user/hubenxia/data/Zika/tophat_zika_Rep_1/accepted_hits.bam,/lustre/user/hubenxia/data/Zika/tophat_zika_Rep_2/accepted_hits.bam  /lustre/user/hubenxia/data/Zika/tophat_mock_Rep_1/accepted_hits.bam,/lustre/user/hubenxia/data/Zika/tophat_mock_Rep_2/accepted_hits.bam  
  

