#!/bin/sh
#PBS -N predict_novel_LncRNAHSV
#PBS -q long
#PBS -l nodes=1:ppn=2
#PBS -o /lustre/user/hubenxia/data/LncRNA-HSV/noncodingRNA/predict_novel_LncRNA.out
#PBS -e /lustre/user/hubenxia/data/LncRNA-HSV/noncodingRNA/predict_novel_LncRNA.err


perl  /lustre/user/hubenxia/data/LncRNA-HSV/noncodingRNA/predict_novel_LncRNA.pl  -input1 /lustre/user/hubenxia/data/HCV/Homo_sapiens.GRCh38/Homo_sapiens.GRCh38.79.gtf  -input2 /lustre/user/hubenxia/data/LncRNA-HSV/noncodingRNA/HSVnovel.combined.gtf    -output /lustre/user/hubenxia/data/LncRNA-HSV/noncodingRNA/LncRNA_ref.gtf
