density(as.numeric(unlist(data$cor)),xlim=c(-1,1))

box<-read.table("exon_fpkm.txt",sep="\t",header=TRUE)
d1<-density(log10(as.numeric(unlist(box[,1]))),na.rm=TRUE)
plot(d1,col="grey11",ylim=c(0,1.5))
d2<-density(log10(as.numeric(unlist(box[,2]))),na.rm=TRUE)
lines(d2,col="red")
d3<-density(log10(as.numeric(unlist(box[,3]))),na.rm=TRUE)
lines(d3,col="DarkBlue")
d4<-density(log10(as.numeric(unlist(box[,4]))),na.rm=TRUE)
lines(d4,col="blue")
d5<-density(log10(as.numeric(unlist(box[,5]))),na.rm=TRUE)
lines(d5,col="green")
d6<-density(log10(as.numeric(unlist(box[,6]))),na.rm=TRUE)
lines(d6,col="Magenta")
legend("topleft",col=c("grey11","red","DarkBlue","blue","green","Magenta"),c("PCGs mock","LncRNAs mock","novellncRNAs mock","PCGs ZIKV","LncRNAs ZIKV","novellncRNAs ZIKV"),lty=c(1,1,1,1,1,1),lwd=3)
axis(2,las=2)

box<-read.table("exon_length.txt",sep="\t",header=TRUE)
d1<-density(log2(as.numeric(unlist(box[,1]))/1000),na.rm=TRUE)
plot(d1,col="grey11",ylim=c(0,0.5))
d2<-density(log2(as.numeric(unlist(box[,2]))/1000),na.rm=TRUE)
lines(d2,col="red")
d3<-density(log2(as.numeric(unlist(box[,3]))/1000),na.rm=TRUE)
lines(d3,col="DarkBlue")
legend("topright",col=c("grey11","red","DarkBlue"),c("PCGs","LncRNAs","novellncRNAs"),lty=c(1,1,1),lwd=3)
